name: Deploy Flask API

on: 
  push:
    branches:
      - main

jobs:

  build-container:

    runs-on: ubuntu-latest

    steps:
    - name: checkout code 
      uses: actions/checkout@v3

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with: 
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
 