name: Deploy Flask API

on: 
  push:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to DockerHub
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push Docker image 
      run: |
       docker build -t hanaparthi/chatapi:latest .  
       docker push hanaparthi/chatapi:latest
    
    - name: Run Docker container
      run: |
       docker run -d -p 3000:3000 hanaparthi/chatapi:latest