on:
  push:
    branches:
      - main

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: hanaparthi
          password: dckr_pat_2GmvHldBFEDUUhvpjTjLSlk7Tnw

  build:
    runs-on: ubuntu-latest
    needs: login
    steps:
      -
        name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./Dockerfile
          push: true
          tags: hanaparthi/chatapi:latest

  port:
    runs-on: ubuntu-latest
    needs: build
    steps:
      -
        name: Run Docker container
        run: docker container run -d -p 3000:3000 hanaparthi/chatapi:latest