name: Deploy Flask API

on: 
  push:
    branches:
      - main

jobs:

  build-container:

    runs-on: ubuntu-latest

    steps:
    - name: checkout code 
      uses: actions/checkout@v3

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with: 
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    
    # - name: Build and push Docker image 
    #   run: |
    #    docker build -t hanaparthi/chatapi:latest .  
    #    docker push hanaparthi/chatapi:latest
    
    # - name: Run Docker container
    #   run: |
    #    docker run -d -p 3000:3000 hanaparthi/chatapi:latest